name : Github Actions Test
on : [push]
jobs : 
      build-app:
        runs-on : ubuntu-latest
        steps :
          - uses : actions/checkout@v2
          - uses : actions/setup-node@v2
            with :
              node-version : '14.17.0'
              yarn-version : latest
          - run : node -v